name: Dynamic GitHub Metrics

on:
  schedule:
    - cron: '0 * * * *'  # Run the workflow every hour
  push:
    branches:
      - main  # Trigger the workflow when there's a push to the main branch

jobs:
  generate-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js (for awesome-readme-stats)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install

      - name: Generate GitHub Metrics
        run: |
          npm run generate-metrics

      - name: Commit and Push metrics update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update dynamic metrics"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
